services:
  bot:
    build: 
          context: ./
          dockerfile: dockerfile
    image: klee-bot
    container_name: klee-bot-container
    working_dir: /var/www/
    volumes:
          - ./:/var/www
    restart: unless-stopped
    ports:
      - "3333:3333"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}



